### ISSUE TITLE
1.19.2 Crash on world load

### ISSUE THREAD

**Issue by Zelioth** [MerchantPug/bovines-and-buttercups#12]
Minecraft 1.19.2
Forge 43.2.4
BAB 1.1.1

Testing an update for my public mod pack and server. loading into a brand new world gives this crash.  appears to be due to one of the classes that spawns the mobs. 

https://gist.github.com/Zelioth/fa380344ef81cc7f676786943918c706

**Comment by ChrysanthCow** [comment]
Quoted from my Discord.
> okay, so it wasn't actually an issue with classes that spawn the mobs.
it was an issue with a Forge event
simply put, I forgot to nullcheck mob effects inside MobEffectEvent.Remove and MobEffectEvent.Expired
