### ISSUE TITLE
[FORGE] Reload command fails with mod installed

### ISSUE THREAD

**Issue by SuspiciousMango** [MerchantPug/bovines-and-buttercups#15]
- B&B version 1.2.0 (but I've encountered this bug in previous versions as well. Unsure when it started)
- MC version 1.19.2
- Forge version 43.2.0

Tested in a new instance with only this mod installed. Using the /reload command to reload datapacks results in this error.
```
[18Feb2023 12:09:00.687] [Server thread/WARN] [net.minecraft.server.commands.ReloadCommand/]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "f_8906_" because the return value of "java.util.function.Supplier.get()" is null
```

the stacktrace eventually shows this line

```
at net.merchantpug.bovinesandbuttercups.BovinesAndButtercupsForge.lambda$addForgeBusEventListeners$9(BovinesAndButtercupsForge.java:149) ~[Bovines-And-Buttercups-Forge-1.2.0+1.19.2.jar%23146!/:1.2.0+1.19.2]
```

I'll also attach the full log for you to take a look at! I'm trying to add this mod to a custom modpack of mine with a LOT of custom recipes, so being able to successfully /reload is super important! Otherwise fantastic mod! Thanks, and hopefully this is an easy fix!

[latest.log](https://github.com/MerchantPug/bovines-and-buttercups/files/10774805/latest.log)

**Comment by ChrysanthCow** [comment]
Will look into it next update

**Comment by ChrysanthCow** [comment]
This fix will be effective as of next update
