### ISSUE TITLE
Startup crash from EMI 1.0.1

### ISSUE THREAD

**Issue by sisby-folk** [MerchantPug/bovines-and-buttercups#18]
Hi hello! the funky EMI integration for status effects has broken and needs suring up on EMI 1.0.1, where it causes a startup crash

https://mclo.gs/MI7bm32

https://github.com/emilyploszaj/emi/issues/198#issuecomment-1572345480

**Comment by ChrysanthCow** [comment]
Quoted from https://github.com/emilyploszaj/emi/issues/198#issuecomment-1573026629
> If you're curious as to why I'm using a mixin, it's because Bovines and Buttercups has an extra tooltip when hovering over the effect inside the menu in survival (as this isn't normal vanilla behaviour to do this), this issue will be fixed when I get to it.

**Comment by ChrysanthCow** [comment]
~~This mixin actually wasn't mandatory, so I'll be removing it as I update to support EMI 1.0.1~~. Thanks for this report.

It probably isn't??? I'll see what I can do.

**Comment by ChrysanthCow** [comment]
Fixed in 1.6.1
