### ISSUE TITLE
[1.20.1] Crash "Rendering entity in world"

### ISSUE THREAD

**Issue by katubug** [MerchantPug/bovines-and-buttercups#22]
Hi, I was doing some testing and when I teleported back to my main testing base, I got this crash: https://gist.github.com/katubug/4aa819f097bbecb025afb5018277aba9

I had had several Mooblooms (yellow and pink) around for a while, but it was only when I teleported away and came back that I got the crash. Unfortunately I don't have the matching latest.log at hand because this was a day or two ago, but if you need it I can try to hunt through them.

This is on B&B 1.9.0, Forge 47.2.19.

**Comment by ChrysanthCow** [comment]
Will look into this later.

**Comment by ChrysanthCow** [comment]
This was only fixed on 1.20.4, re-opening for that reason.
