### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Amber9572** [MerchantPug/bovines-and-buttercups#23]
[latest.log](https://github.com/MerchantPug/bovines-and-buttercups/files/14075084/latest.log)

Here is my log, I've been mo(o)ving to 1.20.2 today and downloaded this file to replace the moobloom mod I had in 1.16.5. I can't make heads or tails of log files, but ATLauncher helpfully marked this mod as causing a fatal error. Hope this helps, and tell me if I should send a more verbose log, as I have my settings to only show the dumbed down info.

**Comment by ChrysanthCow** [comment]
I'll look into this some bit later, sorry for the late response.

**Comment by ChrysanthCow** [comment]
Ah, Bovines and Buttercups isn't available for Forge 1.20.2, I've moved to NeoForge for 1.20.2, anyways, sorry, I don't think I'll be making a Forge jar.
