### ISSUE TITLE
Request: No-Grass Backs

### ISSUE THREAD

**Issue by LunaFabula** [MerchantPug/bovines-and-buttercups#25]
I would like to request a resource pack, built-in perhaps, that removes the grassy backs of the Mooblooms. (I swear that was an option I could choose before....)

At the very least, please consider this.

**Comment by ChrysanthCow** [comment]
There is a resource pack for that. If there isn't, that's a bug.

Which version are you on?

**Comment by LunaFabula** [comment]
Using the latest, I'll double check my resourcepacks. ....Found it. Thanks.
